# Generated by Django 4.2.14 on 2025-08-29 09:40

from django.db import migrations, models
import django.db.models.deletion
import rtsp_cam.models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_cam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='입력하세요', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('task_type', models.CharField(choices=[('감지', '감지'), ('인식', '인식'), ('분류', '분류')], default='감지', max_length=20)),
                ('model_file', models.FileField(upload_to=rtsp_cam.models.upload_to_ai_model)),
                ('metrics', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('name', 'task_type', 'version')},
            },
        ),
        migrations.AddField(
            model_name='rtspcamerasetting',
            name='detection_model',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras_for_detection', to='rtsp_cam.aimodel'),
        ),
        migrations.AddField(
            model_name='rtspcamerasetting',
            name='recognition_model',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras_for_recognition', to='rtsp_cam.aimodel'),
        ),
    ]
