# Generated by Django 4.2.14 on 2025-08-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_cam', '0002_aimodel_rtspcamerasetting_detection_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtspcamerasetting',
            name='detection_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras_for_detection', to='rtsp_cam.aimodel'),
        ),
        migrations.AlterField(
            model_name='rtspcamerasetting',
            name='recognition_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras_for_recognition', to='rtsp_cam.aimodel'),
        ),
    ]
