# Generated by Django 4.2.14 on 2025-08-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_cam', '0003_alter_rtspcamerasetting_detection_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtspcamerasetting',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
