# Generated by Django 4.2.14 on 2025-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtsp_cam', '0004_alter_rtspcamerasetting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='비고',
            field=models.TextField(blank=True, null=True),
        ),
    ]
