# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import messagebox.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(blank=True, max_length=100, null=True)),
                ('참가자', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System_Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_type', models.CharField(choices=[('message', 'message'), ('alarm', 'alarm'), ('notice', 'notice'), ('error', 'error'), ('warning', 'warning'), ('success', 'success'), ('info', 'info')], max_length=20, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.JSONField(blank=True, null=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('read_time', models.DateTimeField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_send', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_save', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_set', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_내용',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('기록시간', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('chatroom_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagebox.chat_room')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=messagebox.models.Chat_file_directory_path)),
                ('chatroom_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagebox.chat_room')),
            ],
        ),
    ]
