# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import 망관리.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='망관리_DB_폐기사유',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('폐기사유_id', models.CharField(default='', max_length=20)),
                ('폐기사유_표시명', models.CharField(default='', max_length=20)),
                ('is_망관리', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='망관리_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('등록자', models.CharField(blank=True, max_length=20, null=True)),
                ('망번호', models.CharField(default='', max_length=20, unique=True)),
                ('고객사', models.CharField(default='', max_length=20)),
                ('현장명', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('문양', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('의장종류', models.CharField(default='', max_length=20)),
                ('할부치수', models.CharField(default='', max_length=20)),
                ('품명', models.CharField(default='', max_length=20)),
                ('file1', models.FileField(blank=True, default='', max_length=254, null=True, upload_to=망관리.models.user_directory_path)),
                ('file2', models.FileField(blank=True, default='', max_length=254, null=True, upload_to=망관리.models.user_directory_path)),
                ('등록일', models.DateTimeField(default=django.utils.timezone.now)),
                ('망사', models.IntegerField(blank=True, default=0, null=True)),
                ('사용구분', models.CharField(default='', max_length=20)),
                ('세부내용', models.TextField(blank=True, null=True)),
                ('비고', models.TextField(blank=True, null=True)),
                ('검색key', models.CharField(default='', max_length=20)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('폐기사유', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('폐기일', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('serial', models.IntegerField(blank=True, default=0, null=True)),
                ('is_등록', models.BooleanField(default=False)),
                ('등록자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
