# Generated by Django 4.2.14 on 2025-06-16 14:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import 샘플관리.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(blank=True, max_length=20, null=True)),
                ('작업형태', models.CharField(blank=True, max_length=20, null=True)),
                ('제작형태', models.CharField(blank=True, max_length=20, null=True)),
                ('소재종류', models.CharField(blank=True, max_length=20, null=True)),
                ('소재Size', models.CharField(blank=True, max_length=20, null=True)),
                ('수량', models.IntegerField(null=True)),
                ('단위', models.CharField(blank=True, max_length=20, null=True)),
                ('대표Process', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('상세Process', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('패턴No', models.CharField(blank=True, max_length=20, null=True)),
                ('비고', models.TextField(blank=True, null=True)),
                ('대표Process_Text', models.TextField(blank=True, null=True)),
                ('상세Process_Text', models.TextField(blank=True, null=True)),
                ('표시순서', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='완료file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=샘플관리.models.샘플완료_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='첨부file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=샘플관리.models.샘플의뢰_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='샘플관리',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('고객사', models.CharField(blank=True, max_length=20, null=True)),
                ('요청건명', models.CharField(blank=True, max_length=100, null=True)),
                ('용도_현장명', models.CharField(blank=True, max_length=100, null=True)),
                ('진행현황', models.CharField(blank=True, max_length=20, null=True)),
                ('납기일', models.DateField(blank=True, null=True)),
                ('요청일', models.DateField(blank=True, null=True)),
                ('납품차수', models.IntegerField(default=1)),
                ('시편', models.IntegerField(default=0)),
                ('NCT', models.IntegerField(default=0)),
                ('절곡', models.IntegerField(default=0)),
                ('조립', models.IntegerField(default=0)),
                ('설치', models.IntegerField(default=0)),
                ('불요', models.BooleanField(default=True)),
                ('Book', models.IntegerField(default=0)),
                ('Board', models.IntegerField(default=0)),
                ('비고', models.TextField(default='')),
                ('현장명', models.CharField(blank=True, max_length=30, null=True)),
                ('EL사', models.CharField(blank=True, max_length=30, null=True)),
                ('구분', models.CharField(blank=True, max_length=30, null=True)),
                ('생산적용시점', models.DateField(blank=True, null=True)),
                ('is_의뢰', models.BooleanField(default=False)),
                ('작성일', models.DateTimeField(blank=True, null=True)),
                ('완료의견', models.TextField(default='')),
                ('is_완료', models.BooleanField(default=False)),
                ('완료일', models.DateTimeField(null=True)),
                ('process_fks', models.ManyToManyField(blank=True, null=True, related_name='Process+', to='샘플관리.process')),
                ('완료file_fks', models.ManyToManyField(blank=True, null=True, related_name='완료file+', to='샘플관리.완료file')),
                ('완료자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_완료자_fk', to=settings.AUTH_USER_MODEL)),
                ('요청자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_요청자_fk', to=settings.AUTH_USER_MODEL)),
                ('첨부file_fks', models.ManyToManyField(blank=True, null=True, related_name='첨부file+', to='샘플관리.첨부file')),
            ],
        ),
    ]
