### dns-admin/values.ymal
replicaCount: 1

image:
  repository: shinwoohipo/drf
  tag: "0.1.0"
  pullPolicy: Always

service:
  name: http
  type: ClusterIP
  port: 9999
  targetPort: 9999  # containerPort 로 mapping됨

command:
  - /py/bin/uwsgi
  - --ini
  - /uwsgi/uwsgi_http.ini

nfs:
  server: nas.host.sh
  path: /volume1/django/192.168.10.249/media
  size: 200Gi

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

### 별도 env.yaml 로 관리함 : update시, 붙여 넣기
### deployment.yaml 에서 env 추가함.
env:
  - name: IS_DOCKER
    value: "true"



volumeMounts:
  - name: uwsgi-data
    mountPath: /tmp/uwsgi
  - name: drf-media
    mountPath: /shapi/media


volumes:
  - name: uwsgi-data
    emptyDir: {}
  - name: drf-media
    persistentVolumeClaim:
      claimName: drf-media-pvc


resources: {}

# nodeSelector:
#   dns-role: "true"

tolerations: []
### deployment.yaml 에서 Affinity 추가함.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: drf.cluster
            operator: In
            values: ["role"]
          - key: env
            operator: In
            values: ["production"]


### ✅ serviceaccount.yaml 용
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

### ✅ ingress-health.yaml 용
### ingress.yaml 에서도  true면 맨 앞단에 추가함.
ingressHealth:
  namePostfix: ingress-health
  enabled: true

### ✅ ingress.yaml 용
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: drf.service.sh
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: drf
              port:
                number: 9999
  tls: []

### ✅ httproute.yaml 용 ==> 단순한거라, 그냥 ingress 사용함.
httpRoute:
  enabled: false

### ✅ hpa.yaml 용
autoscaling:
  enabled: false

