# Generated by Django 4.2.14 on 2025-06-16 15:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='성과평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('평가종류', models.CharField(blank=True, default='개별', max_length=20, null=True)),
                ('평가점수', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='평가설정_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(blank=True, max_length=30, null=True)),
                ('시작', models.DateField(default=datetime.date.today)),
                ('종료', models.DateField(default=datetime.date.today)),
                ('총평가차수', models.IntegerField(default=2)),
                ('점유_역량', models.IntegerField(default=30)),
                ('점유_성과', models.IntegerField(default=50)),
                ('점유_특별', models.IntegerField(default=20)),
                ('차수별_점유', models.JSONField(default={0: 0, 1: 50, 2: 50})),
                ('차수별_유형', models.JSONField(default={0: '개별', 1: '개별', 2: '종합'})),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_시작', models.BooleanField(default=False)),
                ('is_종료', models.BooleanField(default=False)),
                ('등록자_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='평가설정_등록자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='평가체계_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('차수', models.IntegerField(default=0)),
                ('is_참여', models.BooleanField(default=True)),
                ('is_submit', models.BooleanField(default=False)),
                ('평가설정_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='평가체계_평가설정', to='HR평가_V2.평가설정_db')),
                ('평가자', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='평가체계_평가자', to=settings.AUTH_USER_MODEL)),
                ('피평가자', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='평가체계_피평가자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='특별평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('평가종류', models.CharField(blank=True, default='개별', max_length=20, null=True)),
                ('평가점수', models.FloatField(default=0)),
                ('평가체계_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='특별평가_평가체계_fk', to='HR평가_V2.평가체계_db')),
            ],
        ),
        migrations.CreateModel(
            name='역량평가사전_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, default='', help_text='공통역량, 직무역량(공통), 리더십역량 등: 추가 가능', max_length=15, null=True)),
                ('항목', models.CharField(blank=True, default='', help_text='열정, 원칙준수 , .....', max_length=15, null=True)),
                ('정의', models.CharField(blank=True, default='', help_text='......', max_length=255, null=True)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('등록자_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='역량평가사전_등록자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='역량평가_항목_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('차수', models.IntegerField(default=0)),
                ('평가설정_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='역량평가_항목_평가설정_fk', to='HR평가_V2.평가설정_db')),
                ('항목', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='역량평가_항목_항목', to='HR평가_V2.역량평가사전_db')),
            ],
        ),
        migrations.CreateModel(
            name='역량평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('평가종류', models.CharField(blank=True, default='개별', max_length=20, null=True)),
                ('평가점수', models.FloatField(default=0)),
                ('평가체계_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='역량평가_평가체계_fk', to='HR평가_V2.평가체계_db')),
            ],
        ),
        migrations.CreateModel(
            name='세부_특별평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, default='', help_text='품질, 혁신 등', max_length=15, null=True)),
                ('성과', models.TextField(blank=True, default='', help_text='항목 예시 ', null=True)),
                ('가중치', models.IntegerField(blank=True, default=0, help_text='.....', null=True)),
                ('평가점수', models.FloatField(default=0.0)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('특별평가_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_특별평가_fk', to='HR평가_V2.특별평가_db_v2')),
            ],
        ),
        migrations.CreateModel(
            name='세부_역량평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('평가점수', models.FloatField(default=0)),
                ('역량평가_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_역량평가_fk', to='HR평가_V2.역량평가_db_v2')),
                ('항목', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_역량평가_항목', to='HR평가_V2.역량평가_항목_db_v2')),
            ],
        ),
        migrations.CreateModel(
            name='세부_성과평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('과제명', models.CharField(blank=True, max_length=250, null=True)),
                ('과제목표', models.TextField(blank=True, default='', help_text='.....', null=True)),
                ('성과', models.TextField(blank=True, default='', help_text='.....', null=True)),
                ('목표달성률', models.CharField(blank=True, default='', help_text='.....', max_length=250, null=True)),
                ('실행기간', models.CharField(blank=True, default='', help_text='.....', max_length=50, null=True)),
                ('가중치', models.IntegerField(blank=True, default=0, help_text='.....', null=True)),
                ('평가점수', models.FloatField(default=0.0)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('성과평가_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_성과평가_fk', to='HR평가_V2.성과평가_db_v2')),
            ],
        ),
        migrations.AddField(
            model_name='성과평가_db_v2',
            name='평가체계_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='성과평가_평가체계_fk', to='HR평가_V2.평가체계_db'),
        ),
    ]
