# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('정부기관', models.CharField(default='', help_text='국토교통부, 고용노동부, 등으로', max_length=20)),
                ('구분', models.CharField(default='', help_text='공지사항, 보도자료 , 등으로 ', max_length=15)),
                ('제목', models.CharField(default='', help_text='제목', max_length=250)),
                ('등록일', models.DateField(default='', help_text='등록일-datefield형태임', max_length=15)),
                ('링크', models.TextField(default='', help_text='URL PAGE FULL로 입력할 것')),
                ('server기록', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NEWS_LOG_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('server기록', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NEWS_Table_Head_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(blank=True, default='제목', help_text='제목,..등으로 공란은 없이 ,로 구분', max_length=50, null=True)),
                ('등록일', models.CharField(blank=True, default='등록일', help_text='등록일,작성일,등으로 공란은 없이 ,로 구분', max_length=50, null=True)),
                ('제목금지어', models.CharField(blank=True, default='', help_text='공란은 없이 ,로 구분', max_length=254, null=True)),
                ('server기록', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='정부기관_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_id', models.CharField(default='', help_text='moel_news, moel_notice 등으로', max_length=20)),
                ('gov_name', models.CharField(default='', help_text='국토교통부, 고용노동부, 등으로', max_length=20)),
                ('구분', models.CharField(default='', help_text='공지사항, 보도자료 , 등으로 ', max_length=15)),
                ('url', models.CharField(default='', help_text='URL PAGE FULL로 입력할 것', max_length=150)),
                ('suffix_link', models.CharField(blank=True, help_text='URL PAGE FULL로 입력할 것', max_length=150, null=True)),
                ('server기록', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
