# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import 품질경영.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('작업지침', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevator_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('활동현황', models.TextField(blank=True, null=True)),
                ('활동일', models.DateTimeField(blank=True, null=True)),
                ('등록일', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=품질경영.models.처리현황_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Claim_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=품질경영.models.고객요청_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='CS_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('활동현황', models.TextField(blank=True, null=True)),
                ('활동일', models.DateTimeField(blank=True, null=True)),
                ('등록일', models.DateTimeField(blank=True, null=True)),
                ('예정_시작일', models.DateField(blank=True, null=True)),
                ('예정_완료일', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CS_Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el수량', models.IntegerField(default=0)),
                ('운행층수', models.IntegerField(default=0)),
                ('현장명', models.CharField(blank=True, max_length=200, null=True)),
                ('현장주소', models.CharField(blank=True, max_length=200, null=True)),
                ('Elevator사', models.CharField(blank=True, max_length=50, null=True)),
                ('부적합유형', models.CharField(blank=True, max_length=50, null=True)),
                ('불만요청사항', models.TextField(blank=True, null=True)),
                ('고객명', models.CharField(blank=True, max_length=50, null=True)),
                ('고객연락처', models.CharField(blank=True, max_length=50, null=True)),
                ('차수', models.IntegerField(default=1)),
                ('진행현황', models.CharField(blank=True, choices=[('작성', '작성'), ('Open', 'Open'), ('Close', 'Close')], default='작성', max_length=10, null=True)),
                ('품질비용', models.IntegerField(default=0)),
                ('등록자', models.CharField(blank=True, max_length=50, null=True)),
                ('등록일', models.DateTimeField(blank=True, null=True)),
                ('완료자', models.CharField(blank=True, max_length=50, null=True)),
                ('완료일', models.DateTimeField(blank=True, null=True)),
                ('완료요청일', models.DateField(blank=True, null=True)),
                ('el_info_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CS_Claim_el_info_fk', to='elevator_info.elevator_summary_wo설치일')),
                ('등록자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_claim_등록자_set', to=settings.AUTH_USER_MODEL)),
                ('완료자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_claim_완료자_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('첨부파일수', models.IntegerField(default=0)),
                ('제목', models.CharField(blank=True, max_length=100, null=True)),
                ('귀책공정', models.CharField(blank=True, max_length=100, null=True)),
                ('발행번호', models.CharField(blank=True, max_length=20, null=True)),
                ('발생일자', models.DateField(blank=True, null=True)),
                ('발견자', models.CharField(blank=True, max_length=20, null=True)),
                ('고객사', models.CharField(blank=True, max_length=20, null=True)),
                ('작성일자', models.DateField(blank=True, null=True)),
                ('현장명', models.CharField(blank=True, max_length=50, null=True)),
                ('소재', models.CharField(blank=True, max_length=20, null=True)),
                ('의장명', models.CharField(blank=True, max_length=250, null=True)),
                ('OP', models.CharField(blank=True, max_length=20, null=True)),
                ('자재명', models.CharField(blank=True, max_length=20, null=True)),
                ('수량', models.IntegerField(default=0)),
                ('단위', models.CharField(blank=True, max_length=20, null=True)),
                ('부적합상세', models.TextField(blank=True, null=True)),
                ('임시조치방안', models.TextField(blank=True, null=True)),
                ('일정사항', models.TextField(blank=True, null=True)),
                ('is_배포', models.BooleanField(default=False)),
                ('분류', models.CharField(blank=True, max_length=10, null=True)),
                ('구분', models.CharField(blank=True, max_length=10, null=True)),
                ('조치사항', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='부적합_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=품질경영.models.부적합_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='부적합내용',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('품목', models.CharField(blank=True, max_length=250, null=True)),
                ('부적합수량', models.CharField(blank=True, max_length=250, null=True)),
                ('원인', models.CharField(blank=True, max_length=250, null=True)),
                ('귀책부서', models.CharField(blank=True, max_length=250, null=True)),
                ('조치방안', models.CharField(blank=True, max_length=250, null=True)),
                ('조치일정', models.CharField(blank=True, max_length=250, null=True)),
                ('표시순서', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='품질비용',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('소재비', models.IntegerField(default=0)),
                ('의장비', models.IntegerField(default=0)),
                ('판금비', models.IntegerField(default=0)),
                ('설치비', models.IntegerField(default=0)),
                ('운송비', models.IntegerField(default=0)),
                ('코팅비', models.IntegerField(default=0)),
                ('합계', models.IntegerField(default=0)),
                ('NCR_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='품질경영.ncr')),
            ],
        ),
        migrations.AddField(
            model_name='ncr',
            name='contents_fks',
            field=models.ManyToManyField(to='품질경영.부적합내용'),
        ),
        migrations.AddField(
            model_name='ncr',
            name='file_fks',
            field=models.ManyToManyField(to='품질경영.부적합_file'),
        ),
        migrations.AddField(
            model_name='ncr',
            name='작성자_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ncr',
            name='작지_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='작업지침.작업지침'),
        ),
        migrations.CreateModel(
            name='CS_Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el수량', models.IntegerField(default=0)),
                ('운행층수', models.IntegerField(default=0)),
                ('현장명', models.CharField(blank=True, max_length=200, null=True)),
                ('현장주소', models.CharField(blank=True, max_length=200, null=True)),
                ('Elevator사', models.CharField(blank=True, max_length=50, null=True)),
                ('불만요청사항', models.TextField(blank=True, null=True)),
                ('고객명', models.CharField(blank=True, max_length=50, null=True)),
                ('고객연락처', models.CharField(blank=True, max_length=50, null=True)),
                ('차수', models.IntegerField(default=1)),
                ('진행현황', models.CharField(blank=True, choices=[('작성', '작성'), ('Open', 'Open'), ('Close', 'Close')], default='작성', max_length=10, null=True)),
                ('품질비용', models.IntegerField(default=0)),
                ('등록일', models.DateTimeField(blank=True, null=True)),
                ('완료일', models.DateTimeField(blank=True, null=True)),
                ('action_fks', models.ManyToManyField(blank=True, to='품질경영.action')),
                ('claim_file_fks', models.ManyToManyField(blank=True, to='품질경영.claim_file')),
                ('el_info_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator_info.elevator_summary_wo설치일')),
                ('등록자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='등록자_fk', to=settings.AUTH_USER_MODEL)),
                ('완료자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='완료자_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CS_Claim_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=품질경영.models.고객요청_directory_path)),
                ('claim_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_claim_file_set', to='품질경영.cs_claim')),
            ],
        ),
        migrations.CreateModel(
            name='CS_Activity_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=품질경영.models.고객요청_directory_path)),
                ('activity_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_activity_file_set', to='품질경영.cs_activity')),
            ],
        ),
        migrations.AddField(
            model_name='cs_activity',
            name='claim_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_activity_set', to='품질경영.cs_claim'),
        ),
        migrations.AddField(
            model_name='cs_activity',
            name='등록자_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs_activity_등록자_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='action_files',
            field=models.ManyToManyField(to='품질경영.action_file'),
        ),
        migrations.AddField(
            model_name='action',
            name='등록자_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
