# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_mailid', models.CharField(max_length=20, unique=True, verbose_name='user_mailid')),
                ('user_성명', models.CharField(blank=True, max_length=20)),
                ('user_직책', models.CharField(blank=True, max_length=20)),
                ('user_직급', models.CharField(blank=True, max_length=10)),
                ('기본조직1', models.CharField(blank=True, max_length=20)),
                ('기본조직2', models.CharField(blank=True, max_length=20)),
                ('기본조직3', models.CharField(blank=True, max_length=20)),
                ('MBO_표시명_부서', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_mbo_조회자', models.BooleanField(default=False)),
                ('is_mbo_사용자', models.BooleanField(default=False)),
                ('is_mbo_관리자', models.BooleanField(default=False)),
                ('is_일일보고_조회자', models.BooleanField(default=False)),
                ('is_일일보고_사용자', models.BooleanField(default=False)),
                ('is_일일보고_관리자', models.BooleanField(default=False)),
                ('is_망관리_조회자', models.BooleanField(default=False)),
                ('is_망관리_사용자', models.BooleanField(default=False)),
                ('is_망관리_관리자', models.BooleanField(default=False)),
                ('is_디자인의뢰_조회자', models.BooleanField(default=False)),
                ('is_디자인의뢰_의뢰자', models.BooleanField(default=False)),
                ('is_디자인의뢰_접수자', models.BooleanField(default=False)),
                ('is_디자인의뢰_완료자', models.BooleanField(default=False)),
                ('is_디자인의뢰_관리자', models.BooleanField(default=False)),
                ('is_디자인의뢰_대시보드_영업', models.BooleanField(default=False)),
                ('is_디자인의뢰_대시보드_디자인', models.BooleanField(default=False)),
                ('is_차량관리_조회자', models.BooleanField(default=False)),
                ('is_차량관리_사용자', models.BooleanField(default=False)),
                ('is_차량관리_관리자', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Api_App권한',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('api_uri', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('api_url', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('db_field_url', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('표시명_구분', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('표시명_항목', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('비고', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('등록일', models.DateTimeField(auto_now_add=True)),
                ('is_Active', models.BooleanField(default=False)),
                ('is_Run', models.BooleanField(default=False)),
                ('순서', models.IntegerField(default=10000)),
                ('is_dev', models.BooleanField(default=True)),
                ('help_page', models.FileField(blank=True, max_length=254, null=True, upload_to=users.models.help_page_directory_path)),
                ('info_title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('TO_MODEL', models.CharField(blank=True, default='', help_text='모델 경로 (예: app_name.ModelName)', max_length=250, null=True)),
                ('TO_Serializer', models.CharField(blank=True, default='', help_text='시리얼라이저 경로 (예: app_name.SerializerName)', max_length=250, null=True)),
                ('user_pks', models.ManyToManyField(blank=True, null=True, related_name='user_pks_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='App권한',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('user_pks', models.TextField(blank=True, null=True)),
                ('user_names', models.TextField(blank=True, null=True)),
                ('비고', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('등록일', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_Active', models.BooleanField(default=False)),
                ('is_Run', models.BooleanField(default=True)),
                ('순서', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('협력업종', models.CharField(blank=True, help_text='자사, 원자재, 반제품,제품', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestUserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mailid', models.CharField(max_length=20, unique=True, verbose_name='user_mailid')),
                ('user_성명', models.CharField(blank=True, max_length=20)),
                ('user_직책', models.CharField(blank=True, max_length=20)),
                ('user_직급', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User권한',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('mail', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('app_pks', models.TextField(blank=True, null=True)),
                ('비고', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('등록일', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_time', models.DateTimeField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=users.models.error_video_directory_path)),
                ('OS', models.CharField(default='', max_length=100)),
                ('버젼', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('app_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.api_app권한')),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Company_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companydb'),
        ),
        migrations.CreateModel(
            name='Api_App권한_User_M2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_권한', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_권한_users', to='users.api_app권한')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('app_권한', 'user')},
            },
        ),
    ]
