# Generated by Django 4.2.14 on 2025-07-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_app권한_user_m2m_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_app권한',
            name='db_field_url',
        ),
        migrations.RemoveField(
            model_name='api_app권한',
            name='user_pks',
        ),
        migrations.AddField(
            model_name='api_app권한',
            name='lazy_attrs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='api_app권한',
            name='pb_info',
            field=models.JSONField(default=dict),
        ),
    ]
