# Generated by Django 4.2.14 on 2025-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_api_app권한_db_field_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_app권한',
            old_name='pb_info',
            new_name='App_Menus',
        ),
        migrations.AddField(
            model_name='api_app권한',
            name='Table_Menus',
            field=models.JSONField(default=dict),
        ),
    ]
