# Generated by Django 5.2.6 on 2025-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_portal_info_portal_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_info',
            name='order',
            field=models.IntegerField(default=0, help_text='보여주는 순서'),
        ),
        migrations.AlterField(
            model_name='portal_info',
            name='name',
            field=models.CharField(blank=True, default='', help_text='portal 이름', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portal_info',
            name='url',
            field=models.CharField(blank=True, default='', help_text='portal 접근 url', max_length=250, null=True),
        ),
    ]
