# Generated by Django 5.2.6 on 2025-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_portal_info_order_alter_portal_info_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal_info',
            name='logo',
            field=models.ImageField(blank=True, help_text='portal 로고', max_length=254, null=True, upload_to='portal_logo/'),
        ),
    ]
