# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('생산관리', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProductionLine_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='생산관리.productionline')),
                ('확정Branch_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='생산관리.생산계획_확정branch')),
                ('확정자', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SerialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('스캔시간', models.DateTimeField(auto_now_add=True)),
                ('스캔유형', models.CharField(choices=[('IN', '투입'), ('OUT', '완료')], max_length=10)),
                ('ProductionLine_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='생산관리.productionline')),
                ('serial_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='serial.serialdb')),
                ('작업자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['스캔시간'],
            },
        ),
    ]
