# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import 모니터링.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='사내IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=30, null=True)),
                ('IP_주소', models.GenericIPAddressField(null=True, unique=True)),
                ('host_이름', models.CharField(max_length=30, null=True)),
                ('host_설명', models.CharField(max_length=30, null=True)),
                ('MAC_주소', models.CharField(max_length=30, null=True)),
                ('비고', models.CharField(max_length=100, null=True)),
                ('상위IP', models.GenericIPAddressField(null=True)),
                ('rel_x', models.FloatField(null=True)),
                ('rel_y', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='사내IP_PING결과_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=모니터링.models.ping_img_directory_path)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='사내IP_PING결과',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('결과', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('사내IP_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='모니터링.사내ip')),
            ],
        ),
        migrations.CreateModel(
            name='Log_사용App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(max_length=20, null=True)),
                ('app', models.CharField(max_length=30, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
