# Generated by Django 4.2.14 on 2025-08-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_pb_info_api_app권한_app_menus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('모니터링', '0002_apiaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_App_Access_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('app_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.api_app권한')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
