# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JOB_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='job_name', max_length=250)),
                ('job_function', models.CharField(default='scheduler_job.tasks.test_job', max_length=250)),
                ('description', models.TextField(default='description')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redis_channel', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('interval', '인터벌(초 단위 실행)'), ('cron', '크론(특정 시간 실행)')], default='interval', max_length=250)),
                ('job_interval', models.IntegerField(default=1)),
                ('cron_expression', models.CharField(default='cron_expression', max_length=250)),
                ('timeout_seconds', models.IntegerField(default=300, help_text='작업 타임아웃 시간(초)')),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('is_db_log', models.BooleanField(default=False)),
                ('is_db_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_set', to=settings.AUTH_USER_MODEL)),
                ('job_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_info_set', to='scheduler_job.job_info')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler_Job_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', '실행 중'), ('completed', '완료됨'), ('failed', '실패'), ('timeout', '타임아웃'), ('terminated', '강제 종료')], default='running', max_length=20)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_records', to='scheduler_job.scheduler_job')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Scheduler_Job_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('log', models.JSONField(default={})),
                ('execution_time_ms', models.IntegerField(default=0, help_text='작업 소요 시간(msec)')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler_job.scheduler_job')),
            ],
        ),
    ]
