# Generated by Django 4.2.14 on 2025-07-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_job',
            name='job_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_info_set', to='scheduler_job.job_info'),
        ),
        migrations.AlterField(
            model_name='scheduler_job_log',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_job.scheduler_job'),
        ),
    ]
