# Generated by Django 4.2.14 on 2025-08-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_ws_urls_db_name'),
        ('scheduler_job', '0002_alter_scheduler_job_job_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_info',
            name='redis_channel',
        ),
        migrations.AddField(
            model_name='job_info',
            name='ws_url_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ws_url_db_set', to='config.ws_urls_db'),
        ),
    ]
