# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('생산관리', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('창고코드', models.CharField(choices=[('WH20', 'HI 창고'), ('WH30', 'PG 창고'), ('WH40', 'PO 창고')], max_length=4, unique=True, verbose_name='창고 코드')),
                ('창고명', models.CharField(max_length=50, verbose_name='창고명')),
                ('창고설명', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '창고',
                'verbose_name_plural': '창고 목록',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('상태', models.CharField(blank=True, choices=[('IN-READY', '입고대기'), ('IN', '입고'), ('OUT', '출고'), ('OUT-READY', '출고대기')], max_length=10, null=True)),
                ('수량', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('처리시간', models.DateTimeField(blank=True, null=True)),
                ('Proj_No', models.CharField(blank=True, max_length=50)),
                ('비고', models.TextField(blank=True, null=True)),
                ('생성시간', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('생산관리_제품완료_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='생산관리.생산관리_제품완료')),
                ('창고_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='재고관리.warehouse')),
                ('처리자', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('출고처_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='생산관리.판금처_db')),
            ],
            options={
                'verbose_name': '재고',
                'verbose_name_plural': '재고 목록',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이전상태', models.CharField(blank=True, choices=[('IN-READY', '입고대기'), ('IN', '입고'), ('OUT', '출고'), ('OUT-READY', '출고대기')], max_length=10, null=True)),
                ('변경상태', models.CharField(blank=True, choices=[('IN-READY', '입고대기'), ('IN', '입고'), ('OUT', '출고'), ('OUT-READY', '출고대기')], max_length=10, null=True, verbose_name='변경 상태')),
                ('이전수량', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('변경수량', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('변경시간', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('비고', models.TextField(blank=True, null=True, verbose_name='변경사유')),
                ('stock_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='재고관리.stock')),
                ('처리자', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '재고 이력',
                'verbose_name_plural': '재고 이력 목록',
                'ordering': ['-변경시간'],
                'indexes': [models.Index(fields=['stock_fk', '변경시간'], name='재고관리_stockh_stock_f_de42a4_idx'), models.Index(fields=['변경상태', '변경시간'], name='재고관리_stockh_변경상태_cbb99f_idx')],
            },
        ),
    ]
