# Generated by Django 4.2.14 on 2025-06-16 15:11

import HR평가.models_old
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='성과_평가_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('과제명', models.CharField(blank=True, max_length=250, null=True)),
                ('과제목표', models.TextField(blank=True, default='', help_text='.....', null=True)),
                ('성과', models.TextField(blank=True, default='', help_text='.....', null=True)),
                ('목표달성률', models.CharField(blank=True, default='', help_text='.....', max_length=250, null=True)),
                ('실행기간', models.CharField(blank=True, default='', help_text='.....', max_length=50, null=True)),
                ('가중치', models.IntegerField(blank=True, default=0, help_text='.....', null=True)),
                ('평가점수', models.FloatField(default=0.0)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'HR평가_성과_평가_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='종합평가_결과_Old',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('소속', models.CharField(blank=True, default='', help_text='...', max_length=15, null=True)),
                ('성명', models.CharField(blank=True, default='', help_text='...', max_length=15, null=True)),
                ('종합_본인', models.FloatField(default=0.0)),
                ('역량_본인', models.FloatField(default=0.0)),
                ('성과_본인', models.FloatField(default=0.0)),
                ('특별_본인', models.FloatField(default=0.0)),
                ('본인_is제출', models.BooleanField(default=False)),
                ('종합_1차', models.FloatField(default=0.0)),
                ('역량_1차', models.FloatField(default=0.0)),
                ('성과_1차', models.FloatField(default=0.0)),
                ('특별_1차', models.FloatField(default=0.0)),
                ('평가자_1차', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('is_1차제출', models.BooleanField(default=False)),
                ('is_1차완료', models.BooleanField(default=False)),
                ('종합_2차', models.FloatField(default=0.0)),
                ('역량_2차', models.FloatField(default=0.0)),
                ('성과_2차', models.FloatField(default=0.0)),
                ('특별_2차', models.FloatField(default=0.0)),
                ('평가자_2차', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('is_2차제출', models.BooleanField(default=False)),
                ('종합_3차', models.FloatField(default=0.0)),
                ('역량_3차', models.FloatField(default=0.0)),
                ('성과_3차', models.FloatField(default=0.0)),
                ('특별_3차', models.FloatField(default=0.0)),
                ('평가자_3차', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('is_3차제출', models.BooleanField(default=False)),
                ('종합_최종', models.FloatField(default=0.0)),
                ('역량_최종', models.FloatField(default=0.0)),
                ('성과_최종', models.FloatField(default=0.0)),
                ('특별_최종', models.FloatField(default=0.0)),
                ('최종_is정상', models.BooleanField(default=False)),
                ('is_초기세팅', models.BooleanField(default=False)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': '인사평가_v2_종합평가_결과',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='평가설정DB_Old',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('평가제목', models.CharField(blank=True, max_length=30, null=True)),
                ('평가기간_시작', models.DateField(default=datetime.date.today)),
                ('평가기간_종료', models.DateField(default=datetime.date.today)),
                ('평가점유_역량', models.FloatField(default=0.0)),
                ('평가점유_성과', models.FloatField(default=0.0)),
                ('평가점유_특별', models.FloatField(default=0.0)),
                ('평가점유_1차', models.FloatField(default=0.0)),
                ('평가점유_2차', models.FloatField(default=0.0)),
                ('평가점유_3차', models.FloatField(default=0.0)),
                ('등록자', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('역량평가_file', models.FileField(default='', help_text='xlsx file format 필수 : ', max_length=254, upload_to=HR평가.models_old.user_directory_path)),
                ('평가체제_file', models.FileField(default='', help_text='xlsx file format 필수 : ', max_length=254, upload_to=HR평가.models_old.user_directory_path)),
                ('특별평가_file', models.FileField(default='', help_text='xlsx file format 필수 : ', max_length=254, upload_to=HR평가.models_old.user_directory_path)),
                ('is_시작', models.BooleanField(default=False)),
                ('is_종료', models.BooleanField(default=False)),
                ('is_본인평가_세부할당', models.BooleanField(default=False)),
                ('is_1차평가_세부할당', models.BooleanField(default=False)),
                ('공지사항', models.TextField(default='공지사항입니다. 필수사항입니다.', help_text='필수사항입니다')),
            ],
            options={
                'db_table': '인사평가_v2_평가설정db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='성과평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('평가종류', models.CharField(blank=True, default='개별', max_length=20, null=True)),
                ('평가점수', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='역량_평가_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('평가점수', models.FloatField(blank=True, default=0.0, null=True)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='역량평가사전_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, default='', help_text='공통역량, 직무역량(공통), 리더십역량 등: 추가 가능', max_length=15, null=True)),
                ('항목', models.CharField(blank=True, default='', help_text='열정, 원칙준수 , .....', max_length=15, null=True)),
                ('정의', models.CharField(blank=True, default='', help_text='......', max_length=255, null=True)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('등록자_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_역량평가사전_등록자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='특별_평가_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, default='', help_text='품질, 혁신 등', max_length=15, null=True)),
                ('성과', models.TextField(blank=True, default='', help_text='항목 예시 ', null=True)),
                ('가중치', models.IntegerField(blank=True, default=0, help_text='.....', null=True)),
                ('평가점수', models.FloatField(default=0.0)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('등록자_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_특별_평가_등록자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='평가설정_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(blank=True, max_length=30, null=True)),
                ('시작', models.DateField(default=datetime.date.today)),
                ('종료', models.DateField(default=datetime.date.today)),
                ('총평가차수', models.IntegerField(default=2)),
                ('점유_역량', models.IntegerField(default=30)),
                ('점유_성과', models.IntegerField(default=50)),
                ('점유_특별', models.IntegerField(default=20)),
                ('차수별_점유', models.JSONField(default={0: 0, 1: 50, 2: 50})),
                ('차수별_유형', models.JSONField(default={0: '개별', 1: '개별', 2: '종합'})),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_시작', models.BooleanField(default=False)),
                ('is_종료', models.BooleanField(default=False)),
                ('등록자_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_평가설정_등록자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='평가체계_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('차수', models.IntegerField(default=0)),
                ('is_참여', models.BooleanField(default=True)),
                ('is_submit', models.BooleanField(default=False)),
                ('평가설정_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_평가체계_평가설정', to='HR평가.평가설정_db')),
                ('평가자', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_평가체계_평가자', to=settings.AUTH_USER_MODEL)),
                ('피평가자', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_평가체계_피평가자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='평가결과_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('역량점수', models.FloatField(default=0)),
                ('성과점수', models.FloatField(default=0)),
                ('특별점수', models.FloatField(default=0)),
                ('종합점수', models.FloatField(default=0)),
                ('ability_m2m', models.ManyToManyField(related_name='abilty_m2m', to='HR평가.역량_평가_db')),
                ('perform_m2m', models.ManyToManyField(related_name='perform_m2m', to='HR평가.성과_평가_db')),
                ('special_m2m', models.ManyToManyField(related_name='special_m2m', to='HR평가.특별_평가_db')),
                ('평가체계_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='평가자_평가체계_fk', to='HR평가.평가체계_db')),
                ('피평가자_평가체계_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='피평가자_평가체계_fk', to='HR평가.평가체계_db')),
            ],
        ),
        migrations.CreateModel(
            name='특별평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('평가종류', models.CharField(blank=True, default='개별', max_length=20, null=True)),
                ('평가점수', models.FloatField(default=0)),
                ('평가체계_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='특별평가_평가체계_fk', to='HR평가.평가체계_db')),
            ],
        ),
        migrations.AddField(
            model_name='특별_평가_db',
            name='평가설정_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_특별평가_평가설정', to='HR평가.평가설정_db'),
        ),
        migrations.CreateModel(
            name='역량항목_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, max_length=20, null=True)),
                ('item_fks', models.ManyToManyField(related_name='__item_m2m+', to='HR평가.역량평가사전_db')),
                ('평가설정_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_역량평가항목_DB_평가설정', to='HR평가.평가설정_db')),
            ],
        ),
        migrations.CreateModel(
            name='역량평가_항목_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('차수', models.IntegerField(default=0)),
                ('평가설정_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='역량평가_항목_평가설정_fk', to='HR평가.평가설정_db')),
                ('항목', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='역량평가_항목_항목', to='HR평가.역량평가사전_db')),
            ],
        ),
        migrations.CreateModel(
            name='역량평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submit', models.BooleanField(default=False)),
                ('평가종류', models.CharField(blank=True, default='개별', max_length=20, null=True)),
                ('평가점수', models.FloatField(default=0)),
                ('평가체계_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='역량평가_평가체계_fk', to='HR평가.평가체계_db')),
            ],
        ),
        migrations.CreateModel(
            name='역량평가_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('평가점수', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_submit', models.BooleanField(default=False)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('역량평가사전_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_역량평가_역량평가사전', to='HR평가.역량평가사전_db')),
                ('평가체계_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_역량평가_평가체계', to='HR평가.평가체계_db')),
            ],
        ),
        migrations.AddField(
            model_name='역량_평가_db',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='역량평가_역량평가사전', to='HR평가.역량평가사전_db'),
        ),
        migrations.AddField(
            model_name='역량_평가_db',
            name='등록자_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_역량_평가_등록자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='역량_평가_db',
            name='평가설정_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_역량평가_평가설정', to='HR평가.평가설정_db'),
        ),
        migrations.CreateModel(
            name='세부_특별평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, default='', help_text='품질, 혁신 등', max_length=15, null=True)),
                ('성과', models.TextField(blank=True, default='', help_text='항목 예시 ', null=True)),
                ('가중치', models.IntegerField(blank=True, default=0, help_text='.....', null=True)),
                ('평가점수', models.FloatField(default=0.0)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('특별평가_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_특별평가_fk', to='HR평가.특별평가_db_v2')),
            ],
        ),
        migrations.CreateModel(
            name='세부_역량평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('평가점수', models.FloatField(default=0)),
                ('역량평가_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_역량평가_fk', to='HR평가.역량평가_db_v2')),
                ('항목', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_역량평가_항목', to='HR평가.역량평가_항목_db_v2')),
            ],
        ),
        migrations.CreateModel(
            name='세부_성과평가_DB_V2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('과제명', models.CharField(blank=True, max_length=250, null=True)),
                ('과제목표', models.TextField(blank=True, default='', help_text='.....', null=True)),
                ('성과', models.TextField(blank=True, default='', help_text='.....', null=True)),
                ('목표달성률', models.CharField(blank=True, default='', help_text='.....', max_length=250, null=True)),
                ('실행기간', models.CharField(blank=True, default='', help_text='.....', max_length=50, null=True)),
                ('가중치', models.IntegerField(blank=True, default=0, help_text='.....', null=True)),
                ('평가점수', models.FloatField(default=0.0)),
                ('등록일', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('성과평가_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='세부_성과평가_fk', to='HR평가.성과평가_db_v2')),
            ],
        ),
        migrations.AddField(
            model_name='성과평가_db_v2',
            name='평가체계_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='성과평가_평가체계_fk', to='HR평가.평가체계_db'),
        ),
    ]
