# Generated by Django 4.2.14 on 2025-06-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR평가', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='역량_평가_db',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='역량평가_db',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='역량항목_db',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='특별_평가_db',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='평가결과_db',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='성과_평가_db',
            table=None,
        ),
    ]
