# Generated by Django 4.2.14 on 2025-06-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR평가', '0002_alter_역량_평가_db_options_alter_역량평가_db_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='역량_평가_db',
            name='fk',
        ),
        migrations.RemoveField(
            model_name='역량_평가_db',
            name='등록자_fk',
        ),
        migrations.RemoveField(
            model_name='역량_평가_db',
            name='평가설정_fk',
        ),
        migrations.RemoveField(
            model_name='역량평가_db',
            name='역량평가사전_fk',
        ),
        migrations.RemoveField(
            model_name='역량평가_db',
            name='평가체계_fk',
        ),
        migrations.RemoveField(
            model_name='역량항목_db',
            name='item_fks',
        ),
        migrations.RemoveField(
            model_name='역량항목_db',
            name='평가설정_fk',
        ),
        migrations.RemoveField(
            model_name='특별_평가_db',
            name='등록자_fk',
        ),
        migrations.RemoveField(
            model_name='특별_평가_db',
            name='평가설정_fk',
        ),
        migrations.RemoveField(
            model_name='평가결과_db',
            name='ability_m2m',
        ),
        migrations.RemoveField(
            model_name='평가결과_db',
            name='perform_m2m',
        ),
        migrations.RemoveField(
            model_name='평가결과_db',
            name='special_m2m',
        ),
        migrations.RemoveField(
            model_name='평가결과_db',
            name='평가체계_fk',
        ),
        migrations.RemoveField(
            model_name='평가결과_db',
            name='피평가자_평가체계_fk',
        ),
        migrations.DeleteModel(
            name='성과_평가_DB',
        ),
        migrations.DeleteModel(
            name='역량_평가_DB',
        ),
        migrations.DeleteModel(
            name='역량평가_DB',
        ),
        migrations.DeleteModel(
            name='역량항목_DB',
        ),
        migrations.DeleteModel(
            name='특별_평가_DB',
        ),
        migrations.DeleteModel(
            name='평가결과_DB',
        ),
    ]
