# Generated by Django 4.2.14 on 2025-06-16 14:29

import config.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell_Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('tooltip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='H_Header_Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('tooltip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='resources_name', max_length=250)),
                ('file', models.FileField(max_length=255, upload_to=config.models.directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='V_Header_Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('tooltip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WS_URLS_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='group필수', max_length=250)),
                ('channel', models.CharField(default='channel필수', max_length=250)),
                ('name', models.CharField(default='통상적인 이름', max_length=250, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('TO_MODEL', models.CharField(default='', max_length=250)),
                ('is_init', models.BooleanField(default=False)),
                ('app_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ws_urls_db_app_fk', to='users.api_app권한')),
            ],
        ),
        migrations.CreateModel(
            name='TableVHeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.v_header_menus')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableHHeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.h_header_menus')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableCellMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('cell_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.cell_menus')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.table')),
            ],
        ),
        migrations.CreateModel(
            name='Table_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='table_name', max_length=250)),
                ('table_style', models.CharField(blank=True, default=config.models.get_default_table_style, max_length=250, null=True)),
                ('column_name', models.CharField(default='columns_name', max_length=250)),
                ('display_name', models.CharField(default='display_name', max_length=250)),
                ('column_type', models.CharField(default='CharField', max_length=250)),
                ('column_width', models.IntegerField(default=0)),
                ('cell_style', models.JSONField(default=config.models.get_default_cell_style)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('header_menu', models.CharField(blank=True, max_length=250, null=True)),
                ('cell_menu', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.IntegerField(default=0)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.table')),
            ],
        ),
    ]
