# Generated by Django 4.2.14 on 2025-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ws_urls_db',
            name='name',
            field=models.CharField(default='unique 한 통상적인 이름', max_length=250, unique=True),
        ),
    ]
