# Generated by Django 4.2.14 on 2025-08-20 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_ws_urls_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bg', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='색상은 #RRGGBB 또는 #RRGGBBAA 형식이어야 합니다.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$')])),
                ('font', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='색상은 #RRGGBB 또는 #RRGGBBAA 형식이어야 합니다.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='server', max_length=10)),
            ],
        ),
    ]
