# Generated by Django 4.2.14 on 2025-10-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_colorscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisCacheAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Redis Cache Management',
                'verbose_name_plural': 'Redis Cache Management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dummy_table',
                'managed': True,
            },
        ),
    ]
