# Generated by Django 4.2.14 on 2025-06-16 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('생산지시', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(max_length=10)),
                ('설비', models.CharField(default='', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_By_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('출하_type', models.CharField(max_length=20)),
                ('출하일', models.DateField(blank=True, null=True)),
                ('PO일정', models.DateField(null=True)),
                ('판금일정', models.DateField(null=True)),
                ('HI일정', models.DateField(null=True)),
                ('구매일정', models.DateField(null=True)),
                ('생지일정', models.DateField(null=True)),
                ('작지일정', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='생산계획_DDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_출하일', models.IntegerField()),
                ('_PO', models.IntegerField()),
                ('_판금', models.IntegerField()),
                ('_HI', models.IntegerField()),
                ('_구매', models.IntegerField()),
                ('_생지', models.IntegerField()),
                ('_작지', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='생산계획_공정상세',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('공정순서', models.IntegerField(default=0)),
                ('공정명', models.CharField(max_length=100)),
                ('계획일', models.DateField()),
                ('생성일시', models.DateTimeField(auto_now_add=True)),
                ('수정일시', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_HI_complete', models.BooleanField(default=False)),
                ('ProductionLine_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='생산관리.productionline')),
            ],
            options={
                'ordering': ['확정Branch_fk', '공정순서'],
            },
        ),
        migrations.CreateModel(
            name='생산계획_일정관리',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_cage_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_schedule_cage', to='생산관리.schedule_by_types')),
                ('schedule_door_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_schedule_door', to='생산관리.schedule_by_types')),
                ('schedule_jamb_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_schedule_jamb', to='생산관리.schedule_by_types')),
                ('생산지시_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='생산지시.생산지시')),
            ],
        ),
        migrations.CreateModel(
            name='생산계획_확정Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('공정_완료계획일', models.DateField(blank=True, null=True)),
                ('작업명', models.CharField(blank=True, max_length=100, null=True)),
                ('계획수량', models.IntegerField(blank=True, null=True)),
                ('계획등록_timestamp', models.DateTimeField(default=datetime.datetime(2025, 6, 16, 14, 29, 47, 559567))),
                ('is_Active', models.BooleanField(blank=True, null=True)),
                ('schedule_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_확정Branch_set', to='생산관리.schedule_by_types')),
                ('생산지시_process_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_확정Branch_set', to='생산지시.process')),
                ('일정관리_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='일정관리_확정Branch_set', to='생산관리.생산계획_일정관리')),
            ],
        ),
        migrations.CreateModel(
            name='판금처_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('판금처', models.CharField(max_length=100)),
                ('판금처_코드', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='생산실적',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('실적수량', models.IntegerField(default=0)),
                ('시작시간', models.DateTimeField(blank=True, null=True)),
                ('종료시간', models.DateTimeField(blank=True, null=True)),
                ('비고', models.TextField(blank=True, null=True)),
                ('등록일시', models.DateTimeField(auto_now_add=True)),
                ('공정상세_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='실적_set', to='생산관리.생산계획_공정상세')),
                ('작업자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['공정상세_fk', '시작시간'],
            },
        ),
        migrations.CreateModel(
            name='생산관리_제품완료',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('고객사', models.CharField(max_length=15)),
                ('구분', models.CharField(max_length=10)),
                ('Job_Name', models.CharField(max_length=100)),
                ('Proj_No', models.CharField(max_length=100)),
                ('계획수량', models.IntegerField(default=0)),
                ('실적수량', models.IntegerField(default=0)),
                ('소재', models.CharField(max_length=20)),
                ('치수', models.CharField(max_length=20)),
                ('공정명', models.CharField(max_length=100)),
                ('공정구분', models.CharField(max_length=10)),
                ('설비명', models.CharField(max_length=100)),
                ('계획일', models.DateField(blank=True, null=True)),
                ('완료일시', models.DateTimeField(auto_now_add=True)),
                ('비고', models.TextField(blank=True, null=True)),
                ('완료자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('확정Branch_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='제품완료_set', to='생산관리.생산계획_확정branch')),
            ],
        ),
        migrations.AddField(
            model_name='생산계획_공정상세',
            name='확정Branch_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='공정상세_set', to='생산관리.생산계획_확정branch'),
        ),
        migrations.CreateModel(
            name='계획변경이력',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('변경항목', models.CharField(max_length=20)),
                ('이전값', models.CharField(max_length=100)),
                ('변경값', models.CharField(max_length=100)),
                ('변경사유', models.TextField(blank=True, null=True)),
                ('변경일시', models.DateTimeField(auto_now_add=True)),
                ('공정상세_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='변경이력_set', to='생산관리.생산계획_공정상세')),
                ('변경자', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-변경일시'],
            },
        ),
        migrations.AddField(
            model_name='schedule_by_types',
            name='dday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='생산관리.생산계획_dday'),
        ),
        migrations.CreateModel(
            name='Historical생산계획_확정Branch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('공정_완료계획일', models.DateField(blank=True, null=True)),
                ('작업명', models.CharField(blank=True, max_length=100, null=True)),
                ('계획수량', models.IntegerField(blank=True, null=True)),
                ('계획등록_timestamp', models.DateTimeField(default=datetime.datetime(2025, 6, 16, 14, 29, 47, 559567))),
                ('is_Active', models.BooleanField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산관리.schedule_by_types')),
                ('생산지시_process_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산지시.process')),
                ('일정관리_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산관리.생산계획_일정관리')),
            ],
            options={
                'verbose_name': 'historical 생산계획_확정 branch',
                'verbose_name_plural': 'historical 생산계획_확정 branchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historical생산계획_일정관리',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule_cage_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산관리.schedule_by_types')),
                ('schedule_door_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산관리.schedule_by_types')),
                ('schedule_jamb_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산관리.schedule_by_types')),
                ('생산지시_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산지시.생산지시')),
            ],
            options={
                'verbose_name': 'historical 생산계획_일정관리',
                'verbose_name_plural': 'historical 생산계획_일정관리s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSchedule_By_Types',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('출하_type', models.CharField(max_length=20)),
                ('출하일', models.DateField(blank=True, null=True)),
                ('PO일정', models.DateField(null=True)),
                ('판금일정', models.DateField(null=True)),
                ('HI일정', models.DateField(null=True)),
                ('구매일정', models.DateField(null=True)),
                ('생지일정', models.DateField(null=True)),
                ('작지일정', models.DateField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dday', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='생산관리.생산계획_dday')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical schedule_ by_ types',
                'verbose_name_plural': 'historical schedule_ by_ typess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='생산계획_공정상세',
            index=models.Index(fields=['확정Branch_fk', '공정순서'], name='생산관리_생산계획_공_확정Branc_c775ef_idx'),
        ),
        migrations.AddIndex(
            model_name='생산계획_공정상세',
            index=models.Index(fields=['is_active'], name='생산관리_생산계획_공_is_acti_9321fd_idx'),
        ),
        migrations.AddIndex(
            model_name='생산계획_공정상세',
            index=models.Index(fields=['계획일'], name='생산관리_생산계획_공_계획일_48b210_idx'),
        ),
        migrations.AddIndex(
            model_name='생산계획_공정상세',
            index=models.Index(fields=['ProductionLine_fk'], name='생산관리_생산계획_공_Product_4fbbd6_idx'),
        ),
    ]
