# Generated by Django 4.2.14 on 2025-06-16 14:29

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import 공지요청사항.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File_for_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=공지요청사항.models.user_directory_path_요청사항)),
            ],
        ),
        migrations.CreateModel(
            name='공지사항',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(blank=True, max_length=20, null=True)),
                ('시작일', models.DateField(default=datetime.date(2025, 6, 16))),
                ('종료일', models.DateField(default=datetime.date(2025, 6, 16))),
                ('공지내용', ckeditor.fields.RichTextField(null=True)),
                ('is_Popup', models.BooleanField(default=False)),
                ('popup_시작일', models.DateField(blank=True, null=True)),
                ('popup_종료일', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='요청사항_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(default='', max_length=100)),
                ('요청구분', models.CharField(blank=True, max_length=20, null=True)),
                ('내용', models.TextField(blank=True, default='', null=True)),
                ('요청등록일', models.DateField(default=True, null=True)),
                ('처리내용', models.TextField(blank=True, default='', null=True)),
                ('처리일자', models.DateField(blank=True, null=True)),
                ('is_완료', models.BooleanField(blank=True, default=False, null=True)),
                ('files', models.ManyToManyField(blank=True, to='공지요청사항.file_for_request')),
                ('등록자', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='공지사항_Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('공지사항_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='공지요청사항.공지사항')),
            ],
        ),
    ]
