# Generated by Django 4.2.14 on 2025-07-17 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('공지요청사항', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='요청사항_db',
            name='files',
        ),
        migrations.AddField(
            model_name='file_for_request',
            name='요청사항_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='공지요청사항.요청사항_db'),
        ),
        migrations.AlterField(
            model_name='공지사항',
            name='시작일',
            field=models.DateField(default=datetime.date(2025, 7, 17)),
        ),
        migrations.AlterField(
            model_name='공지사항',
            name='종료일',
            field=models.DateField(default=datetime.date(2025, 7, 17)),
        ),
    ]
