# Generated by Django 4.2.14 on 2025-07-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('공지요청사항', '0002_remove_요청사항_db_files_file_for_request_요청사항_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='요청사항_db',
            name='요청등록일',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 17), null=True),
        ),
    ]
