# Generated by Django 4.2.14 on 2025-08-06 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('공지요청사항', '0003_alter_요청사항_db_요청등록일'),
    ]

    operations = [
        migrations.AddField(
            model_name='공지사항',
            name='popup_대상',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='공지사항',
            name='시작일',
            field=models.DateField(default=datetime.date(2025, 8, 6)),
        ),
        migrations.AlterField(
            model_name='공지사항',
            name='종료일',
            field=models.DateField(default=datetime.date(2025, 8, 6)),
        ),
        migrations.AlterField(
            model_name='요청사항_db',
            name='요청등록일',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 6), null=True),
        ),
    ]
