# Generated by Django 4.2.14 on 2025-08-07 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('공지요청사항', '0004_공지사항_popup_대상_alter_공지사항_시작일_alter_공지사항_종료일_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='공지사항',
            name='시작일',
            field=models.DateField(default=datetime.date(2025, 8, 7)),
        ),
        migrations.AlterField(
            model_name='공지사항',
            name='제목',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='공지사항',
            name='종료일',
            field=models.DateField(default=datetime.date(2025, 8, 7)),
        ),
        migrations.AlterField(
            model_name='요청사항_db',
            name='요청등록일',
            field=models.DateField(blank=True, default=datetime.date(2025, 8, 7), null=True),
        ),
    ]
