# Generated by Django 4.2.14 on 2025-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='is_증강',
            field=models.BooleanField(default=False),
        ),
    ]
