# Generated by Django 4.2.14 on 2025-09-10 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_face', '0002_faceimage_is_증강'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
