# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sale_design_manage_v1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevator_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='완료file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.완료_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='의뢰file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.의뢰_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='디자인의뢰',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(max_length=20, null=True)),
                ('고객사', models.CharField(default='', max_length=20)),
                ('현장명', models.TextField(blank=True, null=True)),
                ('el수량', models.IntegerField(blank=True, null=True)),
                ('운행층수', models.IntegerField(blank=True, null=True)),
                ('비고', models.TextField(blank=True, null=True)),
                ('상세내용', models.TextField(blank=True, null=True)),
                ('영업담당자', models.CharField(blank=True, max_length=20, null=True)),
                ('샘플의뢰여부', models.BooleanField(blank=True, null=True)),
                ('의뢰여부', models.BooleanField(blank=True, null=True)),
                ('의뢰일', models.DateTimeField(blank=True, null=True)),
                ('완료요청일', models.DateTimeField(blank=True, null=True)),
                ('등록일', models.DateTimeField(default=django.utils.timezone.now)),
                ('접수일', models.DateTimeField(blank=True, null=True)),
                ('접수디자이너', models.CharField(blank=True, max_length=20, null=True)),
                ('접수여부', models.BooleanField(blank=True, null=True)),
                ('완료디자이너', models.CharField(blank=True, max_length=20, null=True)),
                ('완료여부', models.BooleanField(blank=True, null=True)),
                ('완료일', models.DateTimeField(blank=True, null=True)),
                ('upload_path_1', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.user_directory_path)),
                ('upload_path_2', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.user_directory_path)),
                ('upload_path_3', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.user_directory_path)),
                ('upload_path_4', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.user_directory_path)),
                ('upload_path_5', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.user_directory_path)),
                ('upload_path_6', models.FileField(blank=True, max_length=254, null=True, upload_to=sale_design_manage_v1.models.user_directory_path)),
                ('의뢰차수', models.IntegerField(blank=True, null=True)),
                ('재의뢰사유', models.CharField(blank=True, max_length=254, null=True)),
                ('첨부파일수', models.IntegerField(blank=True, null=True)),
                ('완료파일수', models.IntegerField(blank=True, null=True)),
                ('등록_weekno', models.IntegerField(blank=True, default=0, null=True)),
                ('접수_weekno', models.IntegerField(blank=True, default=0, null=True)),
                ('완료_weekno', models.IntegerField(blank=True, default=0, null=True)),
                ('temp_group_id', models.IntegerField(blank=True, null=True)),
                ('designer_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='designer_user_fk', to=settings.AUTH_USER_MODEL)),
                ('sales_user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_user_fk', to=settings.AUTH_USER_MODEL)),
                ('완료file_fks', models.ManyToManyField(blank=True, related_name='완료file+', to='sale_design_manage_v1.완료file')),
                ('의뢰file_fks', models.ManyToManyField(blank=True, related_name='의뢰file+', to='sale_design_manage_v1.의뢰file')),
                ('현장명_fk', models.ManyToManyField(blank=True, related_name='el현장명+', to='elevator_info.elevator_summary_wo설치일')),
            ],
        ),
        migrations.CreateModel(
            name='Group의뢰',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('현장명', models.CharField(blank=True, max_length=250, null=True)),
                ('group', models.ManyToManyField(blank=True, related_name='group+', to='sale_design_manage_v1.디자인의뢰')),
            ],
        ),
    ]
