# Generated by Django 4.2.14 on 2025-07-02 15:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='차량관리_selector_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('구분', models.CharField(blank=True, default='', help_text='selector DB에 구분요소로, 예로 법인, 공급업체 입니다.', max_length=15, null=True)),
                ('DB_저장_id', models.CharField(blank=True, default='', help_text='DB에 저장될 id로, 예로 상기 법인이 법인이면, (주)신우하이테크, (주)신우폴리텍스 입니다.', max_length=15, null=True)),
                ('selector_표시명', models.CharField(blank=True, default='', help_text='상기 id에 맞는 사용자에게 보여주는 이름입니다.', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='차량관리_기준정보',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('법인명', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('차종', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('차량번호', models.CharField(blank=True, default='', max_length=15, null=True, unique=True)),
                ('타이어규격', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('공급업체', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('차량가격', models.IntegerField(blank=True, default=0, null=True)),
                ('보증금', models.IntegerField(blank=True, default=0, null=True)),
                ('대여료_VAT포함', models.IntegerField(blank=True, default=0, null=True)),
                ('약정운행거리', models.IntegerField(blank=True, default=0, help_text='단위 km입니다.', null=True)),
                ('초과거리부담금', models.FloatField(blank=True, default=0, help_text='단위 원/km입니다.', null=True)),
                ('시작일', models.DateField(default=datetime.date(2025, 7, 2))),
                ('종료일', models.DateField(default=datetime.date(2025, 7, 2))),
                ('is_exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='차량관리_운행DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('일자', models.DateTimeField(default=datetime.datetime(2025, 7, 2, 15, 43, 11, 984549))),
                ('주행거리', models.IntegerField(blank=True, default=0, help_text='정비일 기준 주행거리(km)입니다', null=True)),
                ('정비금액', models.IntegerField(blank=True, default=0, help_text='정비금액입니다.', null=True)),
                ('정비사항', models.TextField(blank=True, default='', null=True)),
                ('비고', models.TextField(blank=True, default='', null=True)),
                ('관련근거', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('담당자_snapshot', models.CharField(blank=True, default='', help_text='이력을 위해 정적 필드 영역입니다.', max_length=15, null=True)),
                ('담당자_fk', models.ForeignKey(blank=True, db_column='담당자_fk', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='차량관리_V2_운행DB_담당자_fk', to=settings.AUTH_USER_MODEL)),
                ('차량번호_fk', models.ForeignKey(db_column='차량번호_fk', help_text='차량번호 foreign-key입니다', on_delete=django.db.models.deletion.DO_NOTHING, to='차량관리_V2.차량관리_기준정보')),
            ],
        ),
        migrations.CreateModel(
            name='차량관리_사용자',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='차량관리_V2_사용자_fk', to=settings.AUTH_USER_MODEL)),
                ('차량관리_기준정보_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='차량관리_V2_기준정보_fk', to='차량관리_V2.차량관리_기준정보')),
            ],
        ),
    ]
