# Generated by Django 4.2.14 on 2025-07-09 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('차량관리_V2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='차량관리_기준정보',
            name='공급업체',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='차량관리_기준정보',
            name='법인명',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='차량관리_기준정보',
            name='시작일',
            field=models.DateField(default=datetime.date(2025, 7, 9)),
        ),
        migrations.AlterField(
            model_name='차량관리_기준정보',
            name='종료일',
            field=models.DateField(default=datetime.date(2025, 7, 9)),
        ),
        migrations.AlterField(
            model_name='차량관리_기준정보',
            name='차종',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='차량관리_기준정보',
            name='타이어규격',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='차량관리_운행db',
            name='일자',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 16, 30, 20, 924181)),
        ),
    ]
