# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='고객사_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('고객사_id', models.CharField(default='', max_length=20)),
                ('고객사_표시명', models.CharField(default='', max_length=20)),
                ('is_영업디자인', models.BooleanField(blank=True, default=False, null=True)),
                ('is_MBO', models.BooleanField(blank=True, default=False, null=True)),
                ('is_망관리', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='망사_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('망사_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('망사_표시명', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_망관리', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='사용구분_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('사용구분_id', models.CharField(default='', max_length=20)),
                ('사용구분_표시명', models.CharField(default='', max_length=20)),
                ('is_망관리', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='의장종류_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('의장종류_id', models.CharField(default='', max_length=20)),
                ('의장종류_표시명', models.CharField(default='', max_length=20)),
                ('is_망관리', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='품명_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('품명_id', models.CharField(default='', max_length=20)),
                ('품명_표시명', models.CharField(default='', max_length=20)),
                ('is_망관리', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='할부치수_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('할부치수_id', models.CharField(default='', max_length=20)),
                ('할부치수_표시명', models.CharField(default='', max_length=20)),
                ('is_망관리', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
