# Generated by Django 4.2.14 on 2025-07-23 16:14

import CS_V2.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elevator_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CS_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('활동현황', models.TextField(blank=True, null=True)),
                ('활동일', models.DateTimeField(blank=True, null=True)),
                ('등록일', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CS_Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el수량', models.IntegerField(default=0)),
                ('운행층수', models.IntegerField(default=0)),
                ('현장명', models.CharField(blank=True, max_length=200, null=True)),
                ('현장주소', models.CharField(blank=True, max_length=200, null=True)),
                ('Elevator사', models.CharField(blank=True, max_length=50, null=True)),
                ('부적합유형', models.CharField(blank=True, max_length=50, null=True)),
                ('불만요청사항', models.TextField(blank=True, null=True)),
                ('고객명', models.CharField(blank=True, max_length=50, null=True)),
                ('고객연락처', models.CharField(blank=True, max_length=50, null=True)),
                ('차수', models.IntegerField(default=1)),
                ('진행현황', models.CharField(blank=True, choices=[('작성', '작성'), ('의뢰', '의뢰'), ('접수', '접수'), ('완료', '완료'), ('반려', '반려')], default='작성', max_length=10, null=True)),
                ('품질비용', models.IntegerField(default=0)),
                ('등록자', models.CharField(blank=True, max_length=50, null=True)),
                ('등록일', models.DateTimeField(blank=True, null=True)),
                ('완료자', models.CharField(blank=True, max_length=50, null=True)),
                ('완료일', models.DateTimeField(blank=True, null=True)),
                ('완료요청일', models.DateField(blank=True, null=True)),
                ('접수일', models.DateTimeField(blank=True, null=True)),
                ('완료목표일', models.DateField(blank=True, null=True)),
                ('접수자', models.CharField(blank=True, max_length=50, null=True)),
                ('진행계획', models.TextField(blank=True, null=True)),
                ('반려사유', models.TextField(blank=True, null=True)),
                ('el_info_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='elevator_info.elevator_summary_wo설치일')),
                ('등록자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('완료자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('접수자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CS_Claim_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=CS_V2.models.고객요청_directory_path)),
                ('claim_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CS_V2.cs_claim')),
            ],
        ),
        migrations.CreateModel(
            name='CS_Activity_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=CS_V2.models.고객요청_directory_path)),
                ('activity_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CS_V2.cs_activity')),
            ],
        ),
        migrations.AddField(
            model_name='cs_activity',
            name='claim_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CS_V2.cs_claim'),
        ),
        migrations.AddField(
            model_name='cs_activity',
            name='등록자_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
