# Generated by Django 4.2.14 on 2025-07-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS_V2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cs_activity',
            name='claim_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CS_Activity_set', to='CS_V2.cs_claim'),
        ),
        migrations.AlterField(
            model_name='cs_activity_file',
            name='activity_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CS_Activity_File_set', to='CS_V2.cs_activity'),
        ),
        migrations.AlterField(
            model_name='cs_claim_file',
            name='claim_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CS_Claim_File_set', to='CS_V2.cs_claim'),
        ),
    ]
