apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "drf.fullname" . }}-media-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.nfs.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
  persistentVolumeReclaimPolicy: Retain