apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drf.fullname" . }}-media-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.size }}
  storageClassName: ""
  volumeName: {{ include "drf.fullname" . }}-media-pv