# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_recognize.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'face_recognize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x61\x63\x65_recognize.proto\"2\n\x0b\x46\x61\x63\x65Request\x12\x13\n\x0bimage_paths\x18\x01 \x03(\t\x12\x0e\n\x06ws_url\x18\x02 \x01(\t\"d\n\rDecisionImage\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\n\n\x02id\x18\x03 \x01(\t\x12\x15\n\rrequest_image\x18\x04 \x01(\t\x12\x10\n\x08\x64\x62_image\x18\x05 \x01(\t\"\x98\x01\n\tFaceReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1a\n\x12recognized_user_id\x18\x02 \x01(\t\x12\x12\n\nsimilarity\x18\x03 \x01(\x02\x12\x12\n\nnum_images\x18\x04 \x01(\x05\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\'\n\x0f\x64\x65\x63ision_images\x18\x06 \x03(\x0b\x32\x0e.DecisionImage28\n\x0b\x46\x61\x63\x65Service\x12)\n\rRecognizeFace\x12\x0c.FaceRequest\x1a\n.FaceReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_recognize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACEREQUEST']._serialized_start=24
  _globals['_FACEREQUEST']._serialized_end=74
  _globals['_DECISIONIMAGE']._serialized_start=76
  _globals['_DECISIONIMAGE']._serialized_end=176
  _globals['_FACEREPLY']._serialized_start=179
  _globals['_FACEREPLY']._serialized_end=331
  _globals['_FACESERVICE']._serialized_start=333
  _globals['_FACESERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
