# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_register.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'face_register.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x61\x63\x65_register.proto\x12\x04\x66\x61\x63\x65\"%\n\tExtraPath\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04path\x18\x02 \x01(\t\"l\n\x13\x46\x61\x63\x65RegisterRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nimage_path\x18\x03 \x01(\t\x12$\n\x0b\x65xtra_paths\x18\x04 \x03(\x0b\x32\x0f.face.ExtraPath\"y\n\x0bStreamEvent\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12)\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1b.face.StreamEvent.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"d\n\x11\x46\x61\x63\x65RegisterReply\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1f\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x11.face.StreamEvent\x12\r\n\x05\x65rror\x18\x04 \x01(\t2Y\n\x13\x46\x61\x63\x65RegisterService\x12\x42\n\x0cRegisterFace\x12\x19.face.FaceRegisterRequest\x1a\x17.face.FaceRegisterReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_register_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMEVENT_DATAENTRY']._loaded_options = None
  _globals['_STREAMEVENT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_EXTRAPATH']._serialized_start=29
  _globals['_EXTRAPATH']._serialized_end=66
  _globals['_FACEREGISTERREQUEST']._serialized_start=68
  _globals['_FACEREGISTERREQUEST']._serialized_end=176
  _globals['_STREAMEVENT']._serialized_start=178
  _globals['_STREAMEVENT']._serialized_end=299
  _globals['_STREAMEVENT_DATAENTRY']._serialized_start=256
  _globals['_STREAMEVENT_DATAENTRY']._serialized_end=299
  _globals['_FACEREGISTERREPLY']._serialized_start=301
  _globals['_FACEREGISTERREPLY']._serialized_end=401
  _globals['_FACEREGISTERSERVICE']._serialized_start=403
  _globals['_FACEREGISTERSERVICE']._serialized_end=492
# @@protoc_insertion_point(module_scope)
