# Generated by Django 4.2.14 on 2025-06-16 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import 일일보고.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISSUE_보고현황',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('대표_보고명', models.CharField(blank=True, max_length=15, null=True)),
                ('대표_보고순서', models.IntegerField(blank=True, default=0, help_text='unique 정수 5자리 입니다. ', null=True)),
                ('보고일', models.DateField(default=datetime.date.today)),
                ('보고건수', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='개인_INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('보고순서', models.IntegerField(blank=True, default=0, help_text='unique 정수 5자리 입니다. ', null=True, unique=True)),
                ('is_전기사용', models.BooleanField(default=False)),
                ('user_fk', models.ForeignKey(db_column='user_fk', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='대표_보고명_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('대표_보고명', models.CharField(blank=True, max_length=15, null=True)),
                ('대표_보고순서', models.IntegerField(blank=True, default=0, help_text='unique 정수 5자리 입니다. ', null=True, unique=True)),
                ('user', models.CharField(blank=True, help_text='사람 이름을 기입하되 ,로 구분 space 없도록', max_length=250, null=True)),
                ('적용일', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='전기사용량_DB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('등록자', models.CharField(blank=True, max_length=15, null=True)),
                ('하이전기_file', models.FileField(default='', max_length=254, upload_to=일일보고.models.user_directory_path)),
                ('폴리전기_file', models.FileField(default='', max_length=254, upload_to=일일보고.models.user_directory_path)),
                ('일자', models.DateField(default=datetime.date(2025, 6, 15))),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='조직_INFO',
            fields=[
                ('조직이름', models.CharField(default='b3563c31e77a4cf3b73b6592041fc4ee', help_text='primary key 입니다.', max_length=30, primary_key=True, serialize=False)),
                ('보고순서', models.IntegerField(blank=True, default=0, help_text='unique 정수 5자리 입니다. ', null=True, unique=True)),
                ('is_이슈보고', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('상급조직_1차', models.CharField(blank=True, max_length=30, null=True)),
                ('상급조직_2차', models.CharField(blank=True, max_length=30, null=True)),
                ('대표_보고명', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='휴일_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('휴일', models.DateField(default=datetime.date.today, unique=True)),
                ('휴일내용', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='개인_보고현황',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('보고일', models.DateField(default=datetime.date.today)),
                ('보고건수', models.IntegerField(blank=True, default=0, null=True)),
                ('등록자_id', models.ForeignKey(blank=True, db_column='등록자_id', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='일일보고.개인_info')),
                ('조직이름_id', models.ForeignKey(blank=True, db_column='조직이름_id', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='일일보고.조직_info')),
            ],
        ),
        migrations.CreateModel(
            name='개인_리스트_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('일자', models.DateField(default=datetime.date.today)),
                ('업무내용', models.TextField(default='')),
                ('업무주기', models.CharField(blank=True, max_length=10, null=True)),
                ('소요시간', models.FloatField(blank=True, default=0, null=True)),
                ('주요산출물', models.TextField(blank=True, default='', null=True)),
                ('비고', models.TextField(blank=True, default='', null=True)),
                ('등록일', models.DateTimeField(default=django.utils.timezone.now)),
                ('등록_weekno', models.IntegerField(blank=True, default=25, null=True)),
                ('등록_month', models.IntegerField(blank=True, default=6, null=True)),
                ('등록_year', models.IntegerField(blank=True, default=2025, null=True)),
                ('등록자_id', models.ForeignKey(db_column='등록자_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='일일보고.개인_info')),
                ('조직이름_id', models.ForeignKey(db_column='조직이름_id', default='', on_delete=django.db.models.deletion.CASCADE, to='일일보고.조직_info')),
            ],
        ),
        migrations.CreateModel(
            name='ISSUE_리스트_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('일자', models.DateField(default=datetime.date.today)),
                ('활동현황', models.TextField(default='')),
                ('세부내용', models.TextField(blank=True, default='', null=True)),
                ('완료예정일', models.DateField(blank=True, null=True)),
                ('진척율', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('유관부서', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('비고', models.TextField(blank=True, default='', null=True)),
                ('등록일', models.DateTimeField(default=django.utils.timezone.now)),
                ('등록_weekno', models.IntegerField(blank=True, default=25, null=True)),
                ('등록_month', models.IntegerField(blank=True, default=6, null=True)),
                ('등록_year', models.IntegerField(blank=True, default=2025, null=True)),
                ('대표_보고명', models.CharField(blank=True, max_length=15, null=True)),
                ('대표_보고순서', models.IntegerField(blank=True, default=0, help_text='unique 정수 5자리 입니다. ', null=True)),
                ('등록자_id', models.ForeignKey(db_column='등록자_id', default=88, on_delete=django.db.models.deletion.CASCADE, to='일일보고.개인_info')),
                ('조직이름_id', models.ForeignKey(db_column='조직이름_id', default='admin', on_delete=django.db.models.deletion.CASCADE, to='일일보고.조직_info')),
            ],
        ),
    ]
