# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('재고관리', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCM_제품',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('상태', models.CharField(choices=[('OUT', '출고'), ('IN', '입고')], max_length=10)),
                ('수량', models.DecimalField(decimal_places=0, max_digits=10)),
                ('생성시간', models.DateTimeField(auto_now_add=True)),
                ('stock_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scms', to='재고관리.stock')),
                ('처리자', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SCM',
                'verbose_name_plural': 'SCM 목록',
            },
        ),
    ]
