# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import 영업수주.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='영업수주_관리',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('기준년월', models.CharField(blank=True, max_length=7, null=True)),
                ('일정file', models.FileField(blank=True, null=True, upload_to=영업수주.models.upload_to_영업수주_일정)),
                ('금액file', models.FileField(blank=True, null=True, upload_to=영업수주.models.upload_to_영업수주_금액)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('비고', models.TextField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('등록자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='영업수주_관리_등록자', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='자재내역_To_의장_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('자재내역', models.CharField(blank=True, max_length=250, null=True)),
                ('의장', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('기준', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='영업수주_일정',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GATE', models.CharField(blank=True, max_length=250, null=True)),
                ('상태', models.CharField(blank=True, max_length=250, null=True)),
                ('프로젝트', models.CharField(blank=True, max_length=250, null=True)),
                ('호기번호', models.CharField(blank=True, max_length=250, null=True)),
                ('현장호기', models.CharField(blank=True, max_length=250, null=True)),
                ('프로젝트명', models.CharField(blank=True, max_length=250, null=True)),
                ('기종', models.CharField(blank=True, max_length=250, null=True)),
                ('사양', models.CharField(blank=True, max_length=250, null=True)),
                ('기계실_출하요청일', models.DateField(blank=True, null=True)),
                ('구조물_출하요청일', models.DateField(blank=True, null=True)),
                ('출입구_출하요청일', models.DateField(blank=True, null=True)),
                ('DOOR_출하요청일', models.DateField(blank=True, null=True)),
                ('CAGE_출하요청일', models.DateField(blank=True, null=True)),
                ('바닥재_출하요청일', models.DateField(blank=True, null=True)),
                ('착공F', models.CharField(blank=True, max_length=250, null=True)),
                ('착공일', models.DateField(blank=True, null=True)),
                ('설치투입일', models.DateField(blank=True, null=True)),
                ('준공예정일', models.DateField(blank=True, null=True)),
                ('준공F', models.CharField(blank=True, max_length=250, null=True)),
                ('준공일', models.DateField(blank=True, null=True)),
                ('지사', models.CharField(blank=True, max_length=250, null=True)),
                ('설치PM', models.CharField(blank=True, max_length=250, null=True)),
                ('협력업체', models.CharField(blank=True, max_length=250, null=True)),
                ('작업팀장', models.CharField(blank=True, max_length=250, null=True)),
                ('양중업체', models.CharField(blank=True, max_length=250, null=True)),
                ('양중팀장', models.CharField(blank=True, max_length=250, null=True)),
                ('상태_1', models.CharField(blank=True, max_length=250, null=True)),
                ('관리_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='영업수주_일정_관리_set', to='영업수주.영업수주_관리')),
            ],
        ),
        migrations.CreateModel(
            name='영업수주_금액',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('발주번호', models.CharField(blank=True, max_length=20, null=True)),
                ('Proj_번호', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('공사_현장명', models.CharField(blank=True, max_length=250, null=True)),
                ('자재번호', models.CharField(blank=True, max_length=250, null=True)),
                ('자재내역', models.CharField(blank=True, max_length=250, null=True)),
                ('호기번호_WBS', models.CharField(blank=True, max_length=250, null=True)),
                ('호기번호', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('단위', models.CharField(blank=True, max_length=250, null=True)),
                ('발주단가', models.IntegerField(default=0)),
                ('발주수량', models.IntegerField(default=0)),
                ('금액', models.IntegerField(default=0)),
                ('발주잔량', models.IntegerField(default=0)),
                ('신우_단가', models.IntegerField(default=0)),
                ('신우_실제금액', models.IntegerField(default=0)),
                ('도면번호', models.CharField(blank=True, max_length=250, null=True)),
                ('현장대수', models.IntegerField(default=0)),
                ('변경납기일', models.DateField(blank=True, null=True)),
                ('최초납기일', models.DateField(blank=True, null=True)),
                ('생산계획일', models.DateTimeField(blank=True, null=True)),
                ('설치협력사', models.CharField(blank=True, max_length=250, null=True)),
                ('출하일자', models.DateField(blank=True, null=True)),
                ('공사주석', models.TextField(blank=True, null=True)),
                ('거래명세서번호', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('관리_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='영업수주_금액_관리_set', to='영업수주.영업수주_관리')),
                ('의장_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='영업수주_금액_자재내역_To_의장_Mapping_set', to='영업수주.자재내역_to_의장_mapping')),
                ('일정_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='영업수주_금액_일정_set', to='영업수주.영업수주_일정')),
            ],
        ),
    ]
