# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='schedule 명칭 ', max_length=100)),
                ('script', models.CharField(default='', help_text='app 실행 script ', max_length=250)),
                ('설명', models.TextField(blank=True, null=True)),
                ('server기록', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Hour_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='schedule 명칭 ', max_length=100)),
                ('schedule', models.TextField(blank=True, help_text='json stringpy하여 저장함', null=True)),
                ('server기록', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='모니터링_schedule.app')),
            ],
        ),
    ]
