# Generated by Django 4.2.14 on 2025-06-16 14:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import 작업지침.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elevator_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('적용부품', models.CharField(blank=True, max_length=30, null=True)),
                ('적용패널', models.CharField(blank=True, max_length=50, null=True)),
                ('Material', models.CharField(blank=True, max_length=30, null=True)),
                ('대표Process', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('상세Process', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('비고', models.TextField(blank=True, null=True)),
                ('대표Process_Text', models.TextField(blank=True, null=True)),
                ('상세Process_Text', models.TextField(blank=True, null=True)),
                ('표시순서', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rendering_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=작업지침.models.rendering_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='결재내용',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('결재결과', models.BooleanField(blank=True, null=True)),
                ('결재의견', models.TextField(blank=True, null=True)),
                ('결재일', models.DateTimeField(blank=True, null=True)),
                ('의뢰일', models.DateTimeField(blank=True, null=True)),
                ('결재자', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='의장도',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=작업지침.models.의장도_directory_path)),
                ('순서', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='첨부file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=작업지침.models.작업지침_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='작업지침',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('구분', models.CharField(blank=True, max_length=20, null=True)),
                ('Proj_No', models.CharField(blank=True, max_length=30, null=True)),
                ('is_배포', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('수량', models.IntegerField(blank=True, null=True)),
                ('납기일', models.DateField(blank=True, null=True)),
                ('작성일', models.DateField(blank=True, null=True)),
                ('고객사', models.CharField(blank=True, max_length=50, null=True)),
                ('담당', models.CharField(blank=True, max_length=50, null=True)),
                ('진행현황', models.CharField(blank=True, max_length=20, null=True)),
                ('고객요청사항', models.CharField(blank=True, max_length=250, null=True)),
                ('고객성향', models.CharField(blank=True, max_length=250, null=True)),
                ('특이사항', models.CharField(blank=True, max_length=250, null=True)),
                ('집중점검항목', models.CharField(blank=True, max_length=250, null=True)),
                ('검사요청사항', models.CharField(blank=True, max_length=250, null=True)),
                ('변경사유_내용', models.TextField(blank=True, null=True)),
                ('Rev', models.IntegerField(default=1)),
                ('Rendering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='작업지침.rendering_file')),
                ('el_info_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='el_info+', to='elevator_info.elevator_summary_wo설치일')),
                ('prev_작지', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='작업지침.작업지침')),
                ('process_fks', models.ManyToManyField(blank=True, null=True, related_name='Process+', to='작업지침.process')),
                ('결재내용_fks', models.ManyToManyField(blank=True, null=True, related_name='결재선+', to='작업지침.결재내용')),
                ('영업담당자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_영업담당자_fk', to=settings.AUTH_USER_MODEL)),
                ('의장도_fks', models.ManyToManyField(blank=True, null=True, related_name='의장도+', to='작업지침.의장도')),
                ('작성자_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_작성자_fk', to=settings.AUTH_USER_MODEL)),
                ('첨부file_fks', models.ManyToManyField(blank=True, null=True, related_name='첨부file+', to='작업지침.첨부file')),
            ],
        ),
        migrations.CreateModel(
            name='Historical작업지침',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('제목', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('구분', models.CharField(blank=True, max_length=20, null=True)),
                ('Proj_No', models.CharField(blank=True, max_length=30, null=True)),
                ('is_배포', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('수량', models.IntegerField(blank=True, null=True)),
                ('납기일', models.DateField(blank=True, null=True)),
                ('작성일', models.DateField(blank=True, null=True)),
                ('고객사', models.CharField(blank=True, max_length=50, null=True)),
                ('담당', models.CharField(blank=True, max_length=50, null=True)),
                ('진행현황', models.CharField(blank=True, max_length=20, null=True)),
                ('고객요청사항', models.CharField(blank=True, max_length=250, null=True)),
                ('고객성향', models.CharField(blank=True, max_length=250, null=True)),
                ('특이사항', models.CharField(blank=True, max_length=250, null=True)),
                ('집중점검항목', models.CharField(blank=True, max_length=250, null=True)),
                ('검사요청사항', models.CharField(blank=True, max_length=250, null=True)),
                ('변경사유_내용', models.TextField(blank=True, null=True)),
                ('Rev', models.IntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Rendering', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='작업지침.rendering_file')),
                ('el_info_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elevator_info.elevator_summary_wo설치일')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prev_작지', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='작업지침.작업지침')),
                ('영업담당자_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('작성자_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 작업지침',
                'verbose_name_plural': 'historical 작업지침s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Group작업지침',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(blank=True, related_name='group+', to='작업지침.작업지침')),
            ],
        ),
    ]
