# Generated by Django 4.2.14 on 2025-06-16 14:29

from django.db import migrations, models
import django.db.models.deletion
import elevator_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csvupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(null=True, upload_to=elevator_info.models.csv_file_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('건물명', models.CharField(max_length=100)),
                ('건물주소', models.CharField(max_length=254)),
                ('건물주소_찾기용', models.CharField(blank=True, max_length=254, null=True)),
                ('loc_x', models.FloatField()),
                ('loc_y', models.FloatField()),
                ('시도', models.CharField(max_length=20)),
                ('시군구', models.CharField(max_length=30)),
                ('승강기고유번호', models.CharField(max_length=20)),
                ('검사유효만료일자', models.DateField(blank=True, null=True)),
                ('승강기구분', models.CharField(blank=True, max_length=30, null=True)),
                ('승강기형식', models.CharField(blank=True, max_length=20, null=True)),
                ('승강기세부형식', models.CharField(blank=True, max_length=20, null=True)),
                ('승강기종류', models.CharField(blank=True, max_length=30, null=True)),
                ('운행층수', models.IntegerField()),
                ('주행길이', models.CharField(blank=True, max_length=10, null=True)),
                ('정격속도', models.CharField(blank=True, max_length=10, null=True)),
                ('적재하중', models.CharField(blank=True, max_length=10, null=True)),
                ('최대정원', models.CharField(blank=True, max_length=10, null=True)),
                ('제조업체', models.CharField(max_length=30)),
                ('유지관리업체', models.CharField(max_length=30)),
                ('운행지상층수', models.CharField(blank=True, max_length=10, null=True)),
                ('운행지하층수', models.CharField(blank=True, max_length=10, null=True)),
                ('건물용도_대', models.CharField(max_length=30)),
                ('건물용도_소', models.CharField(max_length=50)),
                ('기계실유무', models.BooleanField()),
                ('최초설치일자', models.DateField()),
                ('설치일자', models.DateField()),
                ('승강기상태', models.CharField(max_length=20)),
                ('검사결과이력조회코드', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator_시도_시군구',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('시도', models.CharField(max_length=20)),
                ('시군구', models.CharField(max_length=30)),
                ('수량', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ISO3166_KR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=30)),
                ('name_kor', models.CharField(max_length=30)),
                ('name_for_elevator', models.CharField(max_length=30)),
                ('지사', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator_Summary_WO설치일',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('건물명', models.CharField(max_length=100)),
                ('건물주소', models.CharField(max_length=254)),
                ('건물주소_찾기용', models.CharField(blank=True, max_length=254, null=True)),
                ('loc_x', models.FloatField()),
                ('loc_y', models.FloatField()),
                ('시도', models.CharField(max_length=20)),
                ('시군구', models.CharField(max_length=30)),
                ('최초설치일자', models.DateField()),
                ('수량', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('시도_ISO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator_info.iso3166_kr')),
            ],
        ),
        migrations.CreateModel(
            name='Elevator_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('건물명', models.CharField(max_length=100)),
                ('건물주소', models.CharField(max_length=254)),
                ('건물주소_찾기용', models.CharField(blank=True, max_length=254, null=True)),
                ('loc_x', models.FloatField()),
                ('loc_y', models.FloatField()),
                ('시도', models.CharField(max_length=20)),
                ('시군구', models.CharField(max_length=30)),
                ('최초설치일자', models.DateField()),
                ('수량', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('시도_ISO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator_info.iso3166_kr')),
                ('해당_els', models.ManyToManyField(to='elevator_info.elevator')),
            ],
        ),
        migrations.AddField(
            model_name='elevator',
            name='시도_ISO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator_info.iso3166_kr'),
        ),
    ]
