# Generated by Django 4.2.14 on 2025-06-16 14:29

import datetime
from django.db import migrations, models
import release.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release관리',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App이름', models.CharField(blank=True, max_length=30, null=True)),
                ('OS', models.CharField(choices=[('W', 'Windows'), ('L', 'Linux'), ('R', 'RPi')], default='W', max_length=1)),
                ('버젼', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('종류', models.CharField(choices=[('I', '설치용'), ('U', 'Update용')], default='U', max_length=1)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=release.models.release_directory_path)),
                ('is_즉시', models.BooleanField(default=True)),
                ('is_release', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 6, 16, 14, 29, 47, 454973))),
                ('변경사항', models.TextField(default='')),
            ],
        ),
    ]
